### ISSUE TITLE
Ability to customize PDF export options

### ISSUE THREAD

**Issue by SardiSiV** [joshbduncan/word-search-generator#2]
@joshbduncan 
Thank you for creating this!!!
I have been looking for a tool for some time like this and I think I finally found it!

Would it be possible to add some options to the `word-search` cli tool to allow customizing the PDF, related to the PDF font size options?

I print puzzles for some elderly individuals who have vision problems/trouble seeing, and would like to be able to increase the size a bit.

Specifically, I would like to be able to change the following:

1. The size of the font
2. The kind font (i.e. something other than Courier)

I tried downloading the source code and modifying the file `src/word_search_generator/export.py`, but I could not get my changes to show up when I ran `word-search` . 

Are there any instructions on how to create the `word-search` program. I was only able to get this with the `pip install` instructions.

Regards,
SardiSiV

**Comment by SardiSiV** [comment]
Attached is a puzzle with the size that I would be looking to generate. 

Example puzzle: [puzzle_size.pdf](https://github.com/joshbduncan/word-search-generator/files/7190688/puzzle_size.pdf)

Steps to recreate the puzzle:

1. Go to https://api.razzlepuzzles.com/wordsearch
2. Select the 'Medium' difficulty
3. Print the puzzle, deselect the "Headers and Footers" and "Background Graphics"
4. Change the scale to 128
5. Print to PDF
6. Actually print it

Regards,
SardiSiV

**Comment by joshbduncan** [comment]
Hey, glad you found my program useful! I hadn't thought of your use case but it makes perfect sense. Check out my comments below and let me know what you think?

**Size of the font?**
The font size is controlled by the size of the board which is calculated based on the longest word, word count, and level. I set it up this way so that I could ensure the entire puzzle actually fit on the page with the rest of the info.

If you run the command below you'd get a puzzle sized very similar to the sample you referenced.

`word-search here are some words that will show the size -l 2 -k -e pdf`

This creates a level 2 `-l 2` (medium difficulty) puzzle with the words `here are some words that will show the size` and exports a PDF file `-e pdf` that includes the answer key `-k`. You can view the [exported puzzle here](https://www.dropbox.com/s/k2y4k6sg2wvyabl/Word%20Search%202021-09-19T111439.pdf?dl=0).

Now, even though the font is larger it may not be large enough for your use case. And, if you try and scale the PDF my program generates that will cause the borders to go off of the page and this isn't something I had thought about.

I think I will change the PDF layout to be more like your reference. It's simpler and cleaner and I actually like it better. It will also allow me to let the puzzle use more of the available width of the page to maximize the font size.

**Kind of font?**
Yeah, the package I use to create the PDF has sans-serif fonts that match your provided reference. I can add an option to specify font type (sans or sans-serif) when exporting.

👍 Thanks for your suggestions! I'll let you know as soon as I have updates ready!

**Comment by joshbduncan** [comment]
@SardiSiV, I just uploaded Version 1.0.6 to PyPi. You can update your local copy with the following command.

`pip install --upgrade word-search-generator`

Have a look at the new pdf layout and let me know what you think? Thanks again for your feedback!

**Comment by SardiSiV** [comment]
Thanks for the changes. These look great!

The sans-serif font as well as the bold text make them much easier to read.

I'll print out a few and let you know of the results. I'll be snail mailing these so it may be a while before I hear back.

Fairly certain they won't be able to read the Answer Key, but the puzzles I've sent before didn't even have an answer key :laughing:. I wouldn't worry too much about that one.

Regards,
SardiSiV

**Comment by joshbduncan** [comment]
Sounds good!
